### ISSUE TITLE
dependencies can not be resolved when jpi variant is applied

### ISSUE THREAD

**Issue by rpalcolea** [jenkinsci/gradle-jpi-plugin#145]
Hi @sghill @jjohannes 

I was testing out the latest code on master with a local snapshot and found the following issues:

```
Caused by: org.gradle.internal.resolve.ModuleVersionResolveException: Could not resolve jenkinsci:myclient:1.0.
Required by:
    project :
Caused by: org.gradle.internal.component.NoMatchingConfigurationSelectionException: Unable to find a matching variant of jenkinsci:myclient:1.0:
  - Variant 'jpiEmpty' capability jenkinsci:myclient:1.0:
      - Incompatible attribute:
          - Required org.gradle.libraryelements 'classes+resources' and found incompatible value 'jpi'.
      - Other attributes:
          - Required org.gradle.category 'library' but no value provided.
          - Required org.gradle.dependency.bundling 'external' but no value provided.
          - Required org.gradle.jvm.version '11' but no value provided.
          - Found org.gradle.status 'release' but wasn't required.
          - Required org.gradle.usage 'java-api' but no value provided.
	at org.gradle.internal.component.model.AttributeConfigurationSelector.selectConfigurationUsingAttributeMatching(AttributeConfigurationSelector.java:92)
	at org.gradle.internal.component.model.LocalComponentDependencyMetadata.selectConfigurations(LocalComponentDependencyMetadata.java:143)
	at org.gradle.internal.component.local.model.DslOriginDependencyMetadataWrapper.selectConfigurations(DslOriginDependencyMetadataWrapper.java:62)

```

I wrote a quick sample test to show this issue: https://github.com/jenkinsci/gradle-jpi-plugin/commit/b659a8747a5193c0a0924604df9f0a0a5f7276ac

It wonder if this is related to https://github.com/gradle/gradle/blob/b005019321cd46adf27f7dc22726ab8e8ddbdaed/subprojects/core/src/main/java/org/gradle/api/internal/artifacts/JavaEcosystemSupport.java#L202

**Comment by jjohannes** [comment]
@rpalcolea I think supporting Ivy here is a bit more involved as I initially thought. Or it depends on what you need. I missed this:

https://github.com/jenkinsci/gradle-jpi-plugin/commit/04955e224e8fa4b7420bc1fb088376095b700f4b#diff-5ba137277dc35db28b6fc04e57b5199fR22

You are doing

```
if (isIvyResolvedDependency(ctx)) {
  addEmptyJpiVariant(ctx)
} 
```

If you remove that and just do nothing when `isIvyResolvedDependency(ctx)` does everything work then?


The background is, that Ivy is not handled _variant aware_ by default. In contrast to POMs, which follow clear conventions, Ivy is more flexible. So we cannot do a default variant setup as we do for POMs. Instead, for Ivy, we fall back to the _legacy configuration selection_ mechanism.
But as soon as you add variants in a rule, Gradle will go into variant matching mode. But the only variant you have now is the empty JPI variant. For full variant support with Ivy, you would also need more rules for JAR variants etc. but there is no "one-fits-all" solution for that.

Instead, if we add no variant at all, it _should_ work as before.

**Comment by rpalcolea** [comment]
Hi @jjohannes ! Thanks for looking at this! I made the suggested change here: https://github.com/jenkinsci/gradle-jpi-plugin/compare/master...rpalcolea:JpiVariantRule-resolution-issue?expand=1

Unfortunately, this triggers a new issue:

```
> Task :resolveTestDependencies FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':resolveTestDependencies'.
> Could not resolve all files for configuration ':testRuntimeClasspathJenkins'.
   > No variants of jenkinsci:myclient:1.0 match the consumer attributes:
       - jenkinsci:myclient:1.0 configuration default:
           - Incompatible attribute:
               - Required org.gradle.libraryelements 'jpi' and found incompatible value 'jar'.
           - Other attributes:
               - Found artifactType 'jar' but wasn't required.
               - Required org.gradle.category 'library' but no value provided.
               - Found org.gradle.status 'release' but wasn't required.
               - Required org.gradle.usage 'java-runtime' and found compatible value 'java-runtime'.

``` 

My guess is that `TestDependenciesTask` would require special changes/treatment?

**Comment by rpalcolea** [comment]
I believe this is related to https://github.com/jenkinsci/gradle-jpi-plugin/blob/531cc6595da059bc6818c05e60c876191edc4001/src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiPlugin.groovy#L349, thoughts @jjohannes

**Comment by jjohannes** [comment]
So the general problem is that there is no concept for: "we are fine if there is no variant at all for something, then just take nothing".  Our solution was to introduce the _empty JPI variant_ in the rule.

But because of https://github.com/gradle/gradle/issues/11974, this also only works half-backed. You still might end-up with JARs on the classpath. So we filter out the JARs later - for example [here](https://github.com/jenkinsci/gradle-jpi-plugin/blob/96658cfef9b84ddb581135c384fd74e666ccab6a/src/main/groovy/org/jenkinsci/gradle/plugins/jpi/TestDependenciesTask.groovy#L16-L17).

So it is no problem if some JARs (which should be bundled or get bundled) leak onto a "JPI-path". That's why I thought it'll just work here for Ivy.

Problem is now (and I wasn't aware), that a JAR automatically gets the `LIBRARY_ELEMENTS_ATTRIBUTE  == 'jar'` attribute attached by Gradle's Java plugin. Even if it is the result of a non-variant-aware resolution, as it is the case here for Ivy. I am actually not 100% sure why we do that (and if we really have to).

But there is a solution. We can say that for us JARs are compatible with JPIs – because we filter later in any case.

Doing that however, I discovered that the empty variant thing had even more problems as it was also adding the empty variant to real JPI dependencies (with module metadata) and we then had two JPI variants. Only because of some details of how the matching works, the "real" variant was picked over the "empty" one. I had to remove the "empty variant" to make this work but the new fix makes it obsolete anyway.

There is however a slight change in behavior now, but I _think_ it was like this before we did the change. Only one of my new tests showed that.

With the _empt variant_, a dependency chain like this
`a.jpi -> b.jar -> c.jpi` 
would resolve to `a.jpi` (it is cut at the jar)
Now it resolves to `a.jpi` and `c.jpi` (it is not cut, but only flitered)

I thought in practice it would not make a difference. A `jar` depending on a `jpi`...  🤔.
Turns out that is the case for the Jenkin's test harness... 🤷‍♀ 

So here is the proposed change: https://github.com/jjohannes/gradle-jpi-plugin/commit/24898059fdd9747188ea9ca58dfdb6da69457dab

Can you pick that to your branch and double check that everything works for you @rpalcolea?

**Comment by rpalcolea** [comment]
Hey @jjohannes , thanks for looking at this! and fantastic explanation

I pulled this locally and verified the integration tests!

**Comment by rpalcolea** [comment]
Opened https://github.com/jenkinsci/gradle-jpi-plugin/pull/146 and tagged @sghill there
