### ISSUE TITLE
Better error message for running server task when `coreVersion` is not specified

### ISSUE THREAD

**Issue by matejdro** [jenkinsci/gradle-jpi-plugin#148]
When you attempt to run `server` task and you did not specify `coreVersion` property in build.gradle, you get this very useless error message: `No jenkins.war dependency is specified`

I had to search through source code of this plugin to find out that I actually need to specify `coreVersion` property for this functionality to work.

Can you state that in the error message?

**Comment by sghill** [comment]
Thanks for the suggestion, I like this idea and will most likely get to it after the 0.39.0 release.

If you’d like to submit a PR, that would also be appreciated.

**Comment by sghill** [comment]
Providing an update on this since it has been a while.

This is what I expect the error message to look like:

> Cannot query the value of extension 'jenkinsPlugin' property 'coreVersion' because it has no value available.

So far I've added comprehensive test coverage of this property to make refactoring safe. My plan is to migrate `String coreVersion` -> `Property<String> coreVersion`, which does not appear to be a breaking change for groovy buildscript users (the overwhelming majority of use-cases I'm aware of).

The error messaging above comes out of the box from Gradle when using Lazy Properties. It will fail the build when it is accessed without being set, which means anything that causes the `annotationProcessor`, `compileClasspath`, or `testCompileClasspath` to resolve.

Logistically, I think it makes sense to prioritize two existing issues ahead of this:
1. #136 - Requiring this property compels us to update many of the existing tests, which seems like a great time to go ahead and remove the ProjectBuilder tests in favor of the GradleTestKit tests
2. #151 - Gradle's ability to fail when a configuration is resolved also would just work if we updated the Server task to be a JavaExec task that relied on a dedicated configuration instead of manually resolving in the plugin as is done today.
