### ISSUE TITLE
Server does not stop after stopping server task

### ISSUE THREAD

**Issue by matejdro** [jenkinsci/gradle-jpi-plugin#151]
Not sure if this is the issue with the plugin or something on my side, but after stopping the `./gradlew server` task (via CTRL + C), server sometimes remain running in the background. I have to kill gradle's daemon process for it to stop.

This is on Windows 10, gradle 6.2 and jenkins core 2.164.1.

**Comment by sghill** [comment]
Thanks for the report!

I think this is an issue with the `server` task implementation. It's a [DefaultTask](https://docs.gradle.org/6.2.2/dsl/org.gradle.api.DefaultTask.html) that makes the [current thread hang](https://github.com/jenkinsci/gradle-jpi-plugin/blob/master/src/main/groovy/org/jenkinsci/gradle/plugins/jpi/ServerTask.groovy#L69-L70). As a quick fix for now, could you try the [`--no-daemon`](https://docs.gradle.org/6.2.2/userguide/gradle_daemon.html#sec:ways_to_disable_gradle_daemon) switch with `server`?

A better long-term fix would be to extend [JavaExec](https://docs.gradle.org/6.2.2/dsl/org.gradle.api.tasks.JavaExec.html) instead of DefaultTask.

**Comment by matejdro** [comment]
I can confirm that `--no-daemon` works as a workaround, as well as running the task as debug via IntelliJ
